class Locators:

    username = "[name='email']"
    password = "//input[@id='password']"
    Log_in = "//div[contains(@class,'col-md-12')]//button[contains(@class,'btn') and contains(@class,'btn-blue')]"
    Staff_tab = "//a[@id='sn_staff']"
    Add_Employees = "//button[contains(text(),'Add Employees')]"
    first_name = "//input[@id='_asf1']"
    last_name = "//input[@id='_asl1']"
  # first_name2 = "//input[@id='_asf2']"
  # last_name2 = "//input[@id='_asl2']"
    Save_Employees = "//button[@id='_as_save_multiple']"
    Time_Clock = "//a[@id='sn_timeclock']"
    Clock_In = "//a[@id='tc_tl_ci']"
    Clock_Out = "//span[@class='clockOut_help_tag']"
    Log_out = "//img[@id='tr_avatar']"
    Sign_out = "//a[contains(text(),'Sign Out')]"
    EmployeeAdded = "[id='_status']"
    Error_message = "//div[contains(text(),'Your username/email or password is incorrect')]"